org: angelt
service: api-users

provider:
  name: aws
  runtime: python3.12  
  region: us-east-1
  stage: dev  # Definir el entorno como 'dev' para que los nombres de las tablas sean únicos
  memorySize: 128
  timeout: 30
  iam:
    role: arn:aws:iam::542697993719:role/LabRole
  environment:
    # Definir nombres únicos para las tablas usando el stage
    TABLE_NAME_USERS: ${self:provider.stage}-Pt_users  # Nombre único para la tabla de usuarios
    TABLE_NAME_TOKENS: ${self:provider.stage}-Pt_tokens_acceso  # Nombre único para la tabla de tokens

resources:
  Resources:
    # Tabla DynamoDB para usuarios
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_USERS}  # Usar la variable de entorno para el nombre de la tabla
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: country
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        # Índices secundarios globales (si es necesario para búsqueda por country, por ejemplo)
        GlobalSecondaryIndexes:
          - IndexName: CountryIndex
            KeySchema:
              - AttributeName: country
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true  # Habilitar PITR para recuperación ante desastres
    
    # Tabla DynamoDB para tokens
    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_TOKENS}  # Usar la variable de entorno para el nombre de la tabla
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: token
            KeyType: RANGE  # Sort key para los tokens
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true  # Habilitar PITR para recuperación ante desastres

functions:
  # Función para registrar un usuario
  registerUser:
    handler: registerUser.lambda_handler
    events:
      - http:
          path: /users/register
          method: post
          cors: true
          integration: lambda

  # Función para iniciar sesión
  loginUser:
    handler: loginUser.lambda_handler
    events:
      - http:
          path: /users/login
          method: post
          cors: true
          integration: lambda    

  # Función para validar token
  ValidateToken:
    handler: handler.validateTokenHandler

  # Función para cambiar la contraseña
  changePassword:
    handler: changePassword.lambda_handler
    events:
      - http:
          path: /users/change-password
          method: patch
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  # Función para obtener usuarios por país
  getUsersByCountry:
    handler: getAllByCountry.lambda_handler
    events:
      - http:
          path: /users/getallbycountry
          method: get
          cors: true
          integration: lambda

  # Función para obtener usuario por tenant_id
  getUserByTenantId:
    handler: getInfoById.lambda_handler
    events:
      - http:
          path: /users/info
          method: get
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  # Función para cambiar el nombre de usuario
  changeUsername:
    handler: changeUsername.lambda_handler
    events:
      - http:
          path: /users/change-username
          method: patch
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }
